### ISSUE TITLE
ModuleNotFoundError: No module named 'paramiko' 

### ISSUE THREAD

**Issue by F-I-D-O** [lymperis-e/qgis_remote_db_plugin#5]
The plugin fails to activate due to failed paramiko installation:

```
Couldn't load plugin 'remote_db' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'paramiko' 
Traceback (most recent call last):
  File "C:\Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\remote_db\core\Connection.py", line 7, in 
    from .sshtunnel.sshtunnel import SSHTunnelForwarder
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\remote_db\core\sshtunnel\sshtunnel.py", line 55, in 
    import paramiko
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'paramiko'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\remote_db\__init__.py", line 35, in classFactory
    from .remote_db import RemoteDB
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\remote_db\remote_db.py", line 32, in 
    from .core.ConnectionManager import ConnectionManager
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\remote_db\core\ConnectionManager.py", line 3, in 
    from .Connection import Connection
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\remote_db\core\Connection.py", line 14, in 
    from .sshtunnel.sshtunnel import SSHTunnelForwarder
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\remote_db\core\sshtunnel\sshtunnel.py", line 55, in 
    import paramiko
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'paramiko'


Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.34.5-Prizren Prizren, 4b308492 

Python Path:
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:/Users/david/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

I have QGIS as a part of OSGEO on Windows.

**Comment by dajtxx** [comment]
I am sorry I cannot help with Windows but I had the same problem on MacOS and perhaps the solution is similar.

QGIS seems to have its own python installation, so I used pip to install paramiko like this:

```
cd /Applications/QGIS.app/Contents/MacOS/bin
./pip3 install -t /Applications/QGIS.app/Contents/Resources/python/site-packages paramiko
```

**Comment by kannes** [comment]
This is a dupe of https://github.com/lymperis-e/qgis_remote_db_plugin/issues/2

**Comment by santonetti** [comment]
Hello, 
there was an update of paramiko library recently. Check the following link : https://www.paramiko.org/changelog.html

<img width="688" height="254" alt="Image" src="https://github.com/user-attachments/assets/efbfc5a4-8667-422f-9219-b1943faf6205" />

You must specify the version paramiko==3.5.1 in the requirements. The version paramiko==4.0.0 is not compatible anymore with your plugin because DSAKey is not more supported.

**Comment by kannes** [comment]
> Hello, there was an update of paramiko library recently. Check the following link : https://www.paramiko.org/changelog.html
> <img alt="Image" width="688" height="254" src="https://private-user-images.githubusercontent.com/59958730/479556160-efbfc5a4-8667-422f-9219-b1943faf6205.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU2Mzk0NDcsIm5iZiI6MTc1NTYzOTE0NywicGF0aCI6Ii81OTk1ODczMC80Nzk1NTYxNjAtZWZiZmM1YTQtODY2Ny00MjJmLTkyMTktYjE5NDNmYWY2MjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE5VDIxMzIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MGZlMDExOTMyNDNlZTRhMDUxMDg5YzdiNDI4YzE3YTk1NTU3ZTcyYWM1NzU0ODEyOTliOWZjNDUxNmU1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NgwQ8Qr2nNY0kHc3HC9ZGU7Th7M3449Kqgre9-2qpDM">
> 
> You must specify the version paramiko==3.5.1 in the requirements. The version paramiko==4.0.0 is not compatible anymore with your plugin because DSAKey is not more supported.

The author already did a better solution and migrated away from DSA in https://github.com/lymperis-e/qgis_remote_db_plugin/commit/70605238a0b0e41ddfb13b4fcc0daa7532b8d59f
